# Generated by Django 3.1.6 on 2021-02-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=255)),
                ('Slocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.location')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=255)),
                ('tsubject', models.CharField(max_length=255)),
                ('teacher_school', models.ManyToManyField(to='basic.School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.location')),
                ('student_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.school')),
                ('student_teacher', models.ManyToManyField(to='basic.Teacher')),
            ],
        ),
    ]
