# Generated by Django 3.1.6 on 2021-02-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='StudentModel',
        ),
    ]
